name: Tests


on:
  # Triggers the workflow on push events but only for the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# We're only going to have one job, `test` but you can add this
jobs:
  xcode-test:
    name: "Xcode Tests"
    runs-on: macOS-latest

    steps:
      # Checkout the code to the working directory
      - uses: actions/checkout@v2

      # Ensure that Xcode 13 is used for this workflow
      - name: Force Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app

      # Run the tests
      - name: Run the xcode tests
        run: xcodebuild clean test -project ./ExampleApp/ExampleApp.xcodeproj -scheme NavigatorUITests -destination "platform=iOS Simulator,name=iPhone 13,OS=latest"

      # Process the coverage files to only send Navigator coverage
      - name: Xcodebuild Action
        uses: sersoft-gmbh/swift-coverage-action@v2
        with:
          target-name-filter: Navigator

      # Send Coverage data to Codecov
      - name: Upload Coverage to CodeCov
        uses: codecov/codecov-action@v2
